CREATE TABLE TESTE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100)
);
/*
CREATE TABLE FILME (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(100),
	QTD_INGRESSO INTEGER
);

CREATE TABLE INGRESSO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INTEGER,
	ID_FILME INTEGER,
	PRECO_UNITARIO NUMERIC(20,2)
);



INSERT INTO CLIENTE VALUES (1,'Danilo');

INSERT INTO FILME (ID, QTD_INGRESSO,TITULO) VALUES (1,22,'SHREK');

INSERT INTO INGRESSO VALUES (1, 19.99, 1, 1);*/

